name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print system info
        run: uname -a

      - name: Set up Swift
        uses: apple-actions/setup-swift@v2
        
      - name: Run tests
        run: swift test
