name: Swift CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
          
      - name: Install dependencies
        run: |
          sudo gem install cocoapods
          pod install

      - name: Run unit tests
        run: |
          xcodebuild clean test -scheme MyiOS -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' | xcpretty

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3.1
        with:
          name: test-results
          path: ~/Library/Logs/xcodebuild/*.xcresult
