name: CI Workflow

on:
  push:
    branches:
      - master  # Ana branch ismi 'master'

jobs:
  build:
    runs-on: self-hosted  # Self-hosted runner kullanıyoruz

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print system info
        run: uname -a  # Sistem bilgilerini yazdırır

      - name: Install Swift
        run: |
          # Swift toolchain'ı yükle
          brew install swift

      - name: Run tests
        run: swift test  # Testleri çalıştır
